# Generated by Django 5.1.6 on 2026-02-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='balance',
            field=models.FloatField(default=7000),
        ),
    ]
