# Generated by Django 5.1.6 on 2026-02-13 16:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_question_scores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='id',
        ),
        migrations.AddField(
            model_name='question',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
